AWSTemplateFormatVersion: 2010-09-09

Description: |
  Kitten Carousel is a static website application deployed with Apache Web Server on AWS Elastic Compute Cloud (EC2) Instance using AWS Cloudformation Service.

Resources:
  LeventCFNInstance: 
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-08e4e35cccc6189f4
      InstanceType: t2.micro
      KeyName: firstkey # Please use your own key name without .pem
      SecurityGroups: 
        - cfn-sec-group  # Burayı değiştirin lütfen
      Tags:
        - Key: Name
          Value: EnginCfnInstance # Burayı değiştirin lütfen
      UserData: 
        Fn::Base64:
          !Sub |
          #! /bin/bash
          sudo yum update
          sudo yum install httpd -y
          sudo systemctl start httpd
          sudo systemctl enable httpd
          sudo chmod -R 777 var/www/html
          cd var/www/html
          wget https://raw.githubusercontent.com/engin777/my-projects/main/kedi%20projesi/Project-101-kittens-carousel-static-website-ec2/static-web/cat0.jpg
          wget https://raw.githubusercontent.com/engin777/my-projects/main/kedi%20projesi/Project-101-kittens-carousel-static-website-ec2/static-web/cat1.jpg
          wget https://raw.githubusercontent.com/engin777/my-projects/main/kedi%20projesi/Project-101-kittens-carousel-static-website-ec2/static-web/cat2.jpg
          wget https://raw.githubusercontent.com/engin777/my-projects/main/kedi%20projesi/Project-101-kittens-carousel-static-website-ec2/static-web/cat3.png
          wget https://raw.githubusercontent.com/engin777/my-projects/main/kedi%20projesi/Project-101-kittens-carousel-static-website-ec2/static-web/index.html
